### PR TITLE
Fixed table size issues and added CSS to ensure visibility of horizon…

### PR DESCRIPTION
**Pull request by cienvaras**
…tal scroll.

### CODE REVIEW

**Comment by cienvaras** [comment]
Acceptance test:
- [x] Vertical and horizontal scrollbars should always be visible when needed in embedded tables.

**Comment by topicus** [comment]
I have this issue.

screen shot 2015-08-17 at 6 51 18 pm

**Comment by cienvaras** [comment]
@topicus Can you send me the link of the dataset you're using to create the table? I can't reproduce the issue with my test datasets.

**Comment by topicus** [comment]
Seems to be working now. Don't know what happened. Merging this in.

**Pull request merged**
